# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- main

pool:
  name: 'Default'

steps:
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift'
    version: '4.14'
    cmd: 'oc project default'
  displayName: Switch to myapp project
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift'
    version: '4.14.12'
    cmd: 'oc new-app https://github.com/wenshangbei/simple-app.git'
    ignoreFlag: true
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift'
    version: '4.14.12'
    cmd: 'oc expose svc simple-app'
    ignoreFlag: true
  displayName: Create route
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift'
    version: '4.14.12'
    cmd: 'oc start-build simple-app --follow'
  displayName: Start new build
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift'
    version: '4.14.12'
    cmd: 'oc status'